apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/buffer-data/cricket:latest
  labels:
    cloud.googleapis.com/location: us-central1
  name: cricket
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/client-name: cloud-console
    spec:
      containerConcurrency: 80
      containers:
        image: gcr.io/buffer-data/cricket:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 2000m
            memory: 4096Mi
      serviceAccountName: 655891191260-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
